version: '3.8'

services:
  1851-admin-be:
    image: 025212946569.dkr.ecr.us-east-1.amazonaws.com/1851-admin-be-api:d1bb763db29e735b8471ecaedf7b1265bb7ee9e0
    env_file:
      - .env.production.local
    ports:
      - "3005:3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/v1/landing/mapped-domain"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 300s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2.0"
          memory: 3072MB
        reservations:
          cpus: "1.5"
          memory: 2048MB

networks:
  default:
    driver: overlay
