version: '3.8'

services:

  api:
    container_name: 1851-adimin-be-api-dev
    image: 1851-be-api-dev
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile-local
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env      
    depends_on:
      - db
    networks:
      - 1851-admin-be-api 

  db:
    image: postgres:latest
    restart: always
    container_name: 1851-admin-be-api-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./psql-data:/var/lib/postgresql/data:delegated
    networks:
      - 1851-admin-be-api    
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin@123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - 1851-admin-be-api 

  nginx:
    image: nginx:latest
    container_name: 1851-admin-be-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Docker/nginx-local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - 1851-admin-be-api    
      
  


volumes:
  psql-data:
  pgadmin-data:

networks:
  1851-admin-be-api:
    name: 1851-admin-be-api  
