name: "1851_Production-v2"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.sha }}
  APP_REPOSITORY: 1851-admin-be-api

jobs:

      
          
  Deployment:
    name: "Deployment"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update image tag in docker-compose-1851-prod.yaml
        run: |
          sed -i -E "s|(image: [^:]+:).*|\1${{ env.IMAGE_TAG }}|" ./docker-compose-1851-prod.yaml

      - name: Copy updated docker-compose file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./docker-compose-1851-prod.yaml,./env/prod.sh"
          target: "/srv/1851-prod/admin-be-api/"

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            sh /home/ubuntu/dev-ecr-login.sh
            cd /srv/1851-prod/admin-be-api
            sh env/prod.sh
            docker stack deploy --with-registry-auth -c docker-compose-1851-prod.yaml 1851_prod_admin-be-api
        
     
